In [69]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

In [70]:
df = pd.read_csv('Datos_definitivos.csv')

In [71]:
df

Título                     Puesto  \
0                                    data analyst               Data Analyst   
1                   business intelligence analyst      Business Intelligence   
2                                research analyst               Data Analyst   
3        senior program manager analyst relations               Data Analyst   
4                                    data analyst               Data Analyst   
..                                            ...                        ...   
744                      data engineering manager              Data Engineer   
745              senior machine learning engineer  Machine Learning Engineer   
746                      data engineering manager              Data Engineer   
747  it stibo step inhouse product data developer             Data Developer   
748  it stibo step inhouse product data developer             Data Developer   

     sueldo_min  sueldo_max Expertise Empresa Modalidad Sector Ubicación  \
0         50000       70000   Regular     NaN       NaN    NaN    Madrid   
1         50000       70000   Regular     NaN       NaN    NaN    Madrid   
2         30000       50000   Regular     NaN       NaN    NaN    Madrid   
3         50000       70000    Senior     NaN       NaN    NaN    Madrid   
4         50000       70000   Regular     NaN       NaN    NaN    Madrid   
..          ...         ...       ...     ...       ...    ...       ...   
744       30000       50000    Senior     NaN       NaN    NaN  Cataluña   
745       50000       70000    Senior     NaN       NaN    NaN  Cataluña   
746       30000       50000    Senior     NaN       NaN    NaN  Cataluña   
747       50000       70000   Regular     NaN       NaN    NaN  Cataluña   
748       50000       70000   Regular     NaN       NaN    NaN  Cataluña   

                                           Descripción  \
0    Una empresa internacional y dinámica busca un ...   
1    An innovative edtech company is seeking a Busi...   
2    An established industry player is seeking a Re...   
3    Join a forward-thinking company at the forefro...   
4    Join a forward-thinking company as a Data Anal...   
..                                                 ...   
744                                    Sin descripción   
745                                    Sin descripción   
746  Join a forward-thinking company as a Data Engi...   
747  Join a forward-thinking company as an IT Stibo...   
748                                    Sin descripción   

                                             Servicios Otro Idioma EntornoTEC  \
0    ['Tarjeta de restaurante Seguro de salud Segur...         NaN        NaN   
1    ['Flexible hybrid work environment Comprehensi...         NaN        NaN   
2    ['Competitive benefits Career development oppo...         NaN        NaN   
3    ['Equity (Restricted Stock Units)Life Insuranc...         NaN        NaN   
4    ['Flexible working hours Health insurance Life...         NaN        NaN   
..                                                 ...         ...        ...   
744                                                 []         NaN        NaN   
745                                                 []         NaN        NaN   
746  ['Lunch vouchers Health insurance Relocation p...         NaN        NaN   
747  [' Stibo Step S Q L X M L X S D J S O N Data M...         NaN        NaN   
748  [' Stibo S T E P M D M S Q L X M L X S D J S O...         NaN        NaN   

    Beneficios                                Habilidades      Herramientas  \
0          NaN                                        NaN  Excel, Python, R   
1          NaN         Análisis de datos, Data governance           Tableau   
2          NaN  Análisis de datos, Visualización de datos    Excel, Tableau   
3          NaN                                        NaN               NaN   
4          NaN  Análisis de datos, Visualización de datos  Excel, Python, R   
..         ...           

In [4]:
pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SK

In [72]:
from sklearn.preprocessing import LabelEncoder

In [73]:
clase_LabelEncoder = LabelEncoder()

In [75]:
puesto = clase_LabelEncoder.fit_transform(df["Puesto"]) # En este ejemplo estoy usando fit_transform()
df['Puesto']=puesto
expertise = clase_LabelEncoder.fit_transform(df["Expertise"]) # En este ejemplo estoy usando fit_transform()
df['Expertise']=expertise
ubicacion = clase_LabelEncoder.fit_transform(df["Ubicación"]) 
df['Ubicación']= ubicacion
servicios = clase_LabelEncoder.fit_transform(df["Servicios"]) 
df['Servicios']= servicios
habilidades = clase_LabelEncoder.fit_transform(df["Habilidades"]) 
df['Habilidades']= habilidades
herramientas = clase_LabelEncoder.fit_transform(df["Herramientas"]) 
df['Herramientas']= herramientas
educacion = clase_LabelEncoder.fit_transform(df["Educación"]) 
df['Educación']= educacion

In [77]:
df.head(1)

Título  Puesto  sueldo_min  sueldo_max  Expertise Empresa Modalidad  \
0  data analyst       3       50000       70000          3     NaN       NaN   

  Sector  Ubicación                                        Descripción  \
0    NaN          2  Una empresa internacional y dinámica busca un ...   

   Servicios Otro Idioma EntornoTEC Beneficios  Habilidades  Herramientas  \
0        587         NaN        NaN        NaN           77            63   

   Educación  
0         17

In [78]:
df = df.drop(columns=['Título','Empresa','Modalidad','Sector','Descripción','Otro Idioma','EntornoTEC','Beneficios'])

In [79]:
df.head(1)

Puesto  sueldo_min  sueldo_max  Expertise  Ubicación  Servicios  \
0       3       50000       70000          3          2        587   

   Habilidades  Herramientas  Educación  
0           77            63         17

In [82]:
X = np.array(df.drop("Puesto", axis = 1))

y = np.array(df["Puesto"])

X.shape, y.shape

((749, 8), (749,))

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [27]:
df.head(3)

Puesto  sueldo_min  sueldo_max  Expertise Empresa Modalidad Sector  \
0       3       50000       70000          3     NaN       NaN    NaN   
1       1       50000       70000          3     NaN       NaN    NaN   
2       3       30000       50000          3     NaN       NaN    NaN   

   Ubicación                                        Descripción  \
0          2  Una empresa internacional y dinámica busca un ...   
1          2  An innovative edtech company is seeking a Busi...   
2          2  An established industry player is seeking a Re...   

                                           Servicios Otro Idioma EntornoTEC  \
0  ['Tarjeta de restaurante Seguro de salud Segur...         NaN        NaN   
1  ['Flexible hybrid work environment Comprehensi...         NaN        NaN   
2  ['Competitive benefits Career development oppo...         NaN        NaN   

  Beneficios                                Habilidades      Herramientas  \
0        NaN                                        NaN  Excel, Python, R   
1        NaN         Análisis de datos, Data governance           Tableau   
2        NaN  Análisis de datos, Visualización de datos    Excel, Tableau   

           Educación  
0       Licenciatura  
1  Bachelor's degree  
2                NaN

In [80]:
df.isna().sum()

Puesto          0
sueldo_min      0
sueldo_max      0
Expertise       0
Ubicación       0
Servicios       0
Habilidades     0
Herramientas    0
Educación       0
dtype: int64

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 749 entries, 0 to 748
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Puesto        749 non-null    int64
 1   sueldo_min    749 non-null    int64
 2   sueldo_max    749 non-null    int64
 3   Expertise     749 non-null    int64
 4   Ubicación     749 non-null    int64
 5   Servicios     749 non-null    int64
 6   Habilidades   749 non-null    int64
 7   Herramientas  749 non-null    int64
 8   Educación     749 non-null    int64
dtypes: int64(9)
memory usage: 52.8 KB


In [84]:
X_test

array([[50000, 70000,     3, ...,    76,     1,    12],
       [70000, 90000,     3, ...,    77,    98,    19],
       [30000, 50000,     3, ...,    77,    98,    19],
       ...,
       [50000, 70000,     0, ...,    77,    98,    12],
       [30000, 50000,     4, ...,    77,    94,     0],
       [50000, 70000,     2, ...,    77,    97,     0]])

In [85]:
x_scaler = MinMaxScaler()
X_train = x_scaler.fit_transform(X_train)

X_train

array([[0.66666667, 0.66666667, 0.75      , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 0.        , 0.75      , ..., 1.        , 1.        ,
        1.        ],
       [0.33333333, 0.33333333, 0.75      , ..., 0.31168831, 0.67346939,
        0.        ],
       ...,
       [1.        , 1.        , 0.75      , ..., 1.        , 1.        ,
        1.        ],
       [0.33333333, 0.33333333, 0.75      , ..., 1.        , 0.81632653,
        1.        ],
       [0.33333333, 0.33333333, 0.75      , ..., 1.        , 0.31632653,
        1.        ]])

In [86]:
# 3-Nearest Neighbors

model = KNeighborsClassifier(n_neighbors = 3)

model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [87]:
X_test = x_scaler.transform(X_test)

yhat = model.predict(X_test)

yhat

array([ 3,  6,  3,  3,  8,  3,  3,  3,  8,  3,  3,  3,  8,  3,  6,  3,  3,
        3,  8,  3,  3,  6,  8,  3,  3,  6,  2,  3,  8,  8,  6,  3,  3,  3,
        8,  3,  3,  3,  3,  3, 11,  6,  6,  3,  3,  3,  3,  6,  3,  3,  3,
       11,  3,  3,  2,  3,  3,  3,  1,  3,  3,  3,  6,  8,  3,  3,  3,  3,
        8,  8,  3,  6,  6,  3,  6,  3,  8, 11,  3,  3,  3,  3,  3,  3,  3,
       11,  6,  3,  3,  6,  3,  3,  6,  3,  3,  3,  3, 10,  1,  3,  3,  3,
       11,  3,  3,  3,  1,  3,  6,  3,  6,  6,  3,  2,  3,  6,  3,  3,  2,
       11,  8,  6, 10,  3, 11,  3,  3,  3,  3,  3,  6,  3,  8,  6,  8,  8,
        8,  3,  3,  3,  3,  3,  3,  3,  3,  8,  3,  3,  6,  3])

In [88]:
from sklearn.metrics import accuracy_score

print(f"Accuracy: {accuracy_score(y_test, yhat)}")

Accuracy: 0.5


In [89]:
model.predict_proba(X_test)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.33333333,
        0.        ]])

In [90]:
model.kneighbors([X_test[0]])

(array([[0.30168553, 0.37032892, 0.38603425]]), array([[466, 359, 390]]))